name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install test dependencies
      run: sudo apt install -y valgrind

    - name: Install dependencies
      run: make -C tests

    - name: Run check
      run: make -C tests test
